### ISSUE TITLE
Editor dropdown doesn't display correctly in dark mode on Edge 

### ISSUE THREAD

**Issue by coliff** [m5x5/quick-edits#20]
Editor dropdown doesn't display correctly in dark mode on Edge with Windows.

**To Reproduce**
1. Use extension on Edge (not tested on Chrome) when OS is set to dark mode.
2. Click on Editor dropdown.

**Expected behavior**
Dark mode. I think it needs something like this:
```css
@media (prefers-color-scheme: dark) {
  :root {
    color-scheme: dark;
 }
}
```

**Screenshots**

![image](https://github.com/user-attachments/assets/faad6472-76ea-47f3-bea3-a9c3d775c908)
